### ISSUE TITLE
transForm.deserialize, all value are not selected in a multiple select.

### ISSUE THREAD

**Issue by marccollin** [A1rPun/transForm#2]
Hi

i do an ajax call, i received theses data

```
{"contactId":1,"firstName":"Jean","lastName":"Dupuis","address":"234 maple","cityId":737,"phone":{"phoneId":6,"phone":"(450) 231-1212","phoneType":{"phoneTypeId":1,"phoneType":null},"extension":0},"contactCategoryId":3,"contactSubCategoryId":4,"lodgerId":null,"locationIds":[1]}
```

transForm.deserialize("#setupLocationForm", data);

Every information is set in my form except for a select who accept multiple

```
<select id="setupContactLocation" name="locationIds" multiple="multiple" class="form-control">
  <option value="1">Hôpital Charles-Lemoyne, 23 Tashereau, Longueuil</option>
  <option value="2">Pierre boucher, 54 jacques-cartier, Longueuil</option>
</select>
```

value 1 should be selected because value is received is: locationIds

**Comment by A1rPun** [comment]
Hey marccollin,

That is because the value of the multiple is a string ("1") and the passed value is a number (1). transForm uses the [`indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) method which uses strict equality to test the values. I can make an option to loosen up these checks if you want.

**Comment by marccollin** [comment]
That could be nice, because value in a select it's always a string.

**Comment by A1rPun** [comment]
Yeah you are right, the reason I sticked to the strict equality is because for example when you have `value=""` and you pass a 0 that it will select both options:

```
<select name="test" multiple="multiple">
  <option value="">default value</option>
  <option value="0">index 0</option>
  <option value="1">index 1</option>
</select>
```

because ("" == 0) is true and ("0" == 0) is true.

I think it's still a nice addition for transForm.js to not use strictly comparison in most of the cases. So maybe I will make it default and make an option for strictly comparison. I need to test more thing before I implement it though.
