### ISSUE TITLE
Great library

### ISSUE THREAD

**Issue by ericdfields** [A1rPun/transForm#3]
This looks like a great lib. Thank you.

I'm using a react component to manage my forms that returns an object of key/value pairs for the form fields in my form, example: {'object[name]': 'nameValue', 'object[age]': 49}. 

I'd like to leverage your library to structure my object, but I don't need to traverse form elements. Is this possible?

Thank you.

**Comment by A1rPun** [comment]
Hey @ericdfields,

There are 2 solutions you can choose from. The first is using the `serializeCallback` in the `transForm.serialize()` function like this:

```
transForm.serialize('#myForm', null, function(input, value){
  if(input.hasAttribute('data-reactid')){
    //do something with react component and set `val`
    var val;
    //return simple object which will merge into the serialize result object.
    return { name: input.name, value: val }; 
  }
});
```

I have little reactjs experience so I'm not if this will work for you. I will update the documentation about the serialize callback because it doesn't mention the return object.

The second solution is making use of the internal key/value pair convertor to a complex javascript object, for this I need to create an overloaded version for the first param of the `transForm.serialize()` function. I think it is a nice addition to the library. It will look like this:

```
transForm.serialize({'object[name]': 'nameValue', 'object[age]': 49})
```

Thanks for using transForm.js :+1:.

**Comment by ericdfields** [comment]
That second option sounds more like what I’m looking for.

For what it’s worth, my solution for now is to make use of this other library I found that the creator of [formsy-react](https://github.com/christianalfoni/formsy-react <https://github.com/christianalfoni/formsy-react) uses: https://github.com/christianalfoni/form-data-to-object https://github.com/christianalfoni/form-data-to-object

I simply run toObj({‘model[attribute]’: myValue}) and it does what I expect.

Thanks for responding.

**Comment by A1rPun** [comment]
Those libraries are good at transforming objects :). I decided to create another function inspired by the `toObj` syntax instead of making an overload.  I got more changes in transForm so I will push it later today.

**Comment by A1rPun** [comment]
@ericdfields Sorry to have this issue open for a long time, I will close it for now because I will not implement the feature.

If you have any questions regarding this issue or the library feel free to ask 😄
